---
- name: Create and run a nginx container with docker compose
  hosts: all
  gather_facts: yes
  tasks:

    - name: Setup compose file
      become: yes
      ansible.builtin.copy:
        src: files/docker-compose.yml
        dest: /opt/containers/nginx/
        owner: 1000
        group: 1000 
        
    
    - name: Run nginx
      community.docker.docker_compose:
        project_src: /opt/containers/nginx/
        state: present